/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: pafart_ (https://sketchfab.com/pafart_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fortnite-plane-cc1274df0f0845df8da7af3fe3053f57
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import scene from "../assets/3d/plane.glb";

export function Plane(props) {
  const { nodes, materials } = useGLTF(scene);
  return (
    <group {...props} dispose={null}>
      <group scale={0.011}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          geometry={nodes.Object_7.geometry}
          material={materials.M_Vehicle_FuelLevel}
          skeleton={nodes.Object_7.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_8.geometry}
          material={materials.MI_Biplane_Parts}
          skeleton={nodes.Object_8.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_9.geometry}
          material={materials.MI_Biplane_Base}
          skeleton={nodes.Object_9.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('../assets/3d/plane.glb');
