/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: irons3th (https://sketchfab.com/irons3th)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/unreal-engine-4-sky-be1fae4d5c6e43bbb4970bde465304d0
Title: Unreal Engine 4 Sky
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import scene from "../assets/3d/sky.glb";

export function Sky(props) {
  const { nodes, materials } = useGLTF(scene);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.M_Sky_Panning_Clouds2}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload(scene);
